//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividades
    {
        public int id_actividad { get; set; }
        public string actividad { get; set; }
        public string produccion { get; set; }
        public string lugar { get; set; }
        public int porcentaje_inicial { get; set; }
        public int porcentaje_final { get; set; }
        public bool cacei { get; set; }
        public bool cuerpo_academico { get; set; }
        public bool iso { get; set; }
        public int id_paad { get; set; }
        public Nullable<int> id_iad { get; set; }
    
        public virtual IADs IADs { get; set; }
        public virtual PAADs PAADs { get; set; }
    }
}
