//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrativos
    {
        public int id_administrativo { get; set; }
        public int carrera { get; set; }
        public int rol { get; set; }
        public Nullable<int> docente { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
    
        public virtual Carreras Carreras { get; set; }
        public virtual Docentes Docentes { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
