//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_PAAD_IADEntities : DbContext
    {
        public DB_PAAD_IADEntities()
            : base("name=DB_PAAD_IADEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actividades> Actividades { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<Carreras> Carreras { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Fechas> Fechas { get; set; }
        public virtual DbSet<IADs> IADs { get; set; }
        public virtual DbSet<PAADs> PAADs { get; set; }
        public virtual DbSet<Periodos> Periodos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Docentes> Docentes { get; set; }
    }
}
