//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docente_Rol
    {
        public int id_docente_rol { get; set; }
        public int docente { get; set; }
        public int rol { get; set; }
    
        public virtual Docentes Docentes { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
