//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fechas
    {
        public int id_fechas { get; set; }
        public int periodo { get; set; }
        public System.DateTime inicio { get; set; }
        public System.DateTime fin { get; set; }
    
        public virtual Periodos Periodos { get; set; }
    }
}
