//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IADs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IADs()
        {
            this.Actividades = new HashSet<Actividades>();
            this.Mensajes = new HashSet<Mensajes>();
        }
    
        public int id_iad { get; set; }
        public int estado { get; set; }
        public int periodo { get; set; }
        public int carrera { get; set; }
        public int docente { get; set; }
        public int categoria_docente { get; set; }
        public int horas_clase { get; set; }
        public int horas_investigacion { get; set; }
        public int horas_gestion { get; set; }
        public int horas_tutorias { get; set; }
        public int cargo { get; set; }
        public string firma_docente { get; set; }
        public string firma_director { get; set; }
        public string comentarios { get; set; }
        public bool extemporaneo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actividades> Actividades { get; set; }
        public virtual Cargos Cargos { get; set; }
        public virtual Carreras Carreras { get; set; }
        public virtual Categorias Categorias { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Periodos Periodos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mensajes> Mensajes { get; set; }
        public virtual Docentes Docentes { get; set; }
    }
}
