//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensajes
    {
        public int id_mensaje { get; set; }
        public Nullable<int> paad { get; set; }
        public Nullable<int> iad { get; set; }
        public int tipo { get; set; }
        public string mensaje { get; set; }
    
        public virtual IADs IADs { get; set; }
        public virtual PAADs PAADs { get; set; }
        public virtual TiposDeMensaje TiposDeMensaje { get; set; }
    }
}
