//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Periodos()
        {
            this.IADs = new HashSet<IADs>();
            this.PAADs = new HashSet<PAADs>();
        }
    
        public int id_periodo { get; set; }
        public string periodo { get; set; }
        public bool activo { get; set; }
        public Nullable<System.DateTime> paad_inicio { get; set; }
        public Nullable<System.DateTime> paad_fin { get; set; }
        public Nullable<System.DateTime> iad_inicio { get; set; }
        public Nullable<System.DateTime> iad_fin { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IADs> IADs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAADs> PAADs { get; set; }
    }
}
